create table stops (id integer not null auto_increment, latitude float(53), longtitude float(53), name varchar(255), primary key (id)) engine=InnoDB;
create table stops (id integer not null auto_increment, latitude float(53), longtitude float(53), name varchar(255), primary key (id)) engine=InnoDB;
create table stops (id integer not null auto_increment, latitude float(53), longtitude float(53), name varchar(255), primary key (id)) engine=InnoDB;
create table stops (id integer not null auto_increment, latitude float(53), longtitude float(53), name varchar(255), primary key (id)) engine=InnoDB;
create table stops (id integer generated by default as identity, latitude float(53), longtitude float(53), name varchar(255), primary key (id));
create table stops (id integer generated by default as identity, latitude float(53), longtitude float(53), name varchar(255), primary key (id));
create table stops (id integer generated by default as identity, latitude float(53), longtitude float(53), name varchar(255), primary key (id));
create table stops (id integer generated by default as identity, latitude float(53), longtitude float(53), name varchar(255), primary key (id));
create table stops (id integer generated by default as identity, latitude float(53), longtitude float(53), name varchar(255), primary key (id));
create table stop (id integer generated by default as identity, latitude float(53), longtitude float(53), name varchar(255), primary key (id));
create table stops (id integer not null auto_increment, latitude float(53), longtitude float(53), name varchar(255), primary key (id)) engine=InnoDB;
create table stops (id integer generated by default as identity, latitude float(53), longtitude float(53), name varchar(255), primary key (id));
create table stops (id integer generated by default as identity, latitude float(53), longtitude float(53), name varchar(255), primary key (id));
create table stops (id integer generated by default as identity, latitude float(53), longtitude float(53), name varchar(255), primary key (id));
create table stops (id integer generated by default as identity, latitude float(53), longtitude float(53), name varchar(255), primary key (id));
create table stops (id integer generated by default as identity, latitude float(53), longtitude float(53), name varchar(255), primary key (id));
create table stops (id integer generated by default as identity, latitude float(53), longtitude float(53), name varchar(255), primary key (id));
create table stops (id integer generated by default as identity, latitude float(53), longtitude float(53), name varchar(255), primary key (id));
create table stops (id integer generated by default as identity, latitude float(53), longtitude float(53), name varchar(255), primary key (id));
create table stops (id integer generated by default as identity, latitude float(53), longtitude float(53), name varchar(255), primary key (id));
create table stops (id integer not null auto_increment, latitude float(53), longtitude float(53), name varchar(255), primary key (id)) engine=InnoDB;
create table stops (id integer generated by default as identity, latitude float(53), longtitude float(53), name varchar(255), primary key (id));
create table stops (id integer generated by default as identity, latitude float(53), longtitude float(53), name varchar(255), primary key (id));
create table stops (id integer generated by default as identity, latitude float(53), longtitude float(53), name varchar(255), primary key (id));
create table stops (id integer generated by default as identity, latitude float(53), longtitude float(53), name varchar(255), primary key (id));
create table stops (id integer generated by default as identity, latitude float(53), longtitude float(53), name varchar(255), primary key (id));
create table stops (id integer not null auto_increment, latitude float(53), longtitude float(53), name varchar(255), primary key (id)) engine=InnoDB;

    create table stops (
        id integer generated by default as identity,
        latitude float(53),
        longtitude float(53),
        name varchar(255),
        primary key (id)
    );

    create table stops (
        id integer generated by default as identity,
        latitude float(53),
        longtitude float(53),
        name varchar(255),
        primary key (id)
    );

    create table stops (
        id integer generated by default as identity,
        latitude float(53),
        longtitude float(53),
        name varchar(255),
        primary key (id)
    );

    create table stops (
        id integer generated by default as identity,
        latitude float(53),
        longtitude float(53),
        name varchar(255),
        primary key (id)
    );

    create table stops (
        id integer generated by default as identity,
        latitude float(53),
        longtitude float(53),
        name varchar(255),
        primary key (id)
    );

    create table stops (
        id integer generated by default as identity,
        latitude float(53),
        longtitude float(53),
        name varchar(255),
        primary key (id)
    );

    create table stops (
        id integer generated by default as identity,
        latitude float(53),
        longtitude float(53),
        name varchar(255),
        primary key (id)
    );

    create table stops (
        id integer generated by default as identity,
        latitude float(53),
        longtitude float(53),
        name varchar(255),
        primary key (id)
    );

    create table stops (
        id integer generated by default as identity,
        latitude float(53),
        longtitude float(53),
        name varchar(255),
        primary key (id)
    );

    create table stops (
        id integer generated by default as identity,
        latitude float(53),
        longtitude float(53),
        name varchar(255),
        primary key (id)
    );

    create table stops (
        id integer generated by default as identity,
        latitude float(53),
        longtitude float(53),
        name varchar(255),
        primary key (id)
    );
create table stops (id integer not null auto_increment, latitude float(53), longtitude float(53), name varchar(255), primary key (id)) engine=InnoDB;

    create table stops (
        id integer generated by default as identity,
        latitude float(53),
        longtitude float(53),
        name varchar(255),
        primary key (id)
    );

    create table stops (
        id integer generated by default as identity,
        latitude float(53),
        longtitude float(53),
        name varchar(255),
        primary key (id)
    );
create table stops (id integer generated by default as identity, latitude float(53), longtitude float(53), name varchar(255), primary key (id));

    create table stops (
        id integer generated by default as identity,
        latitude float(53),
        longtitude float(53),
        name varchar(255),
        primary key (id)
    );

    create table stops (
        id integer generated by default as identity,
        latitude float(53),
        longtitude float(53),
        name varchar(255),
        primary key (id)
    );

    create table stops (
        id integer generated by default as identity,
        latitude float(53),
        longtitude float(53),
        name varchar(255),
        primary key (id)
    );

    create table stops (
        id integer generated by default as identity,
        latitude float(53),
        longtitude float(53),
        name varchar(255),
        primary key (id)
    );

    create table stops (
        id integer generated by default as identity,
        latitude float(53),
        longtitude float(53),
        name varchar(255),
        primary key (id)
    );

    create table stops (
        id integer generated by default as identity,
        latitude float(53),
        longtitude float(53),
        name varchar(255),
        primary key (id)
    );
create table stops (id integer generated by default as identity, latitude float(53), longtitude float(53), name varchar(255), primary key (id));
create table stops (id integer generated by default as identity, latitude float(53), longtitude float(53), name varchar(255), primary key (id));
create table stops (id integer generated by default as identity, latitude float(53), longtitude float(53), name varchar(255), primary key (id));
